apiVersion: apps/v1
kind: Deployment
metadata:
  name: bk-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: backend
        image: kushaggarwal/backend:latest
        ports:
        - containerPort: 4000
